<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #395796; padding-bottom: 10px; margin-bottom: 20px; }
        .clinic-title { font-size: 24px; color: #395796; margin: 0; }
        .section-header { background: #f8fafc; color: #395796; padding: 10px; font-weight: bold; text-transform: uppercase; margin-top: 25px; border-left: 5px solid #E97F95; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 10px; border: 1px solid #e2e8f0; text-align: left; font-size: 12px; }
        th { background-color: #f1f5f9; font-weight: bold; width: 30%; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="clinic-title">Clinic Registration Details</h1>
        <p>Customer ID: <strong>{{ $clinic->customer_id }}</strong> | Date: {{ date('d M, Y') }}</p>
    </div>

    <div class="section-header">Clinic Information</div>
    <table>
        <tr><th>Clinic Name</th><td>{{ $clinic->name }}</td></tr>
        <tr><th>Login Email</th><td>{{ $clinic->email }}</td></tr>
        <tr><th>AMC Status</th><td>{{ $clinic->is_active ? 'ACTIVE' : 'INACTIVE' }}</td></tr>
        <tr><th>Address</th><td>{{ $clinic->address_line_1 }}, {{ $clinic->state }}, {{ $clinic->country }} {{ $clinic->zip_code }}</td></tr>
        <tr><th>Expiry Date</th><td>{{ $clinic->exp_date ?? 'Lifetime' }}</td></tr>
    </table>

    <div class="section-header">Primary Contacts</div>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clinic->contacts as $contact)
            <tr>
                <td>{{ $contact->name }}</td>
                <td>{{ $contact->position }}</td>
                <td>{{ $contact->phone }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($clinic->branches->count() > 0)
    <div class="section-header">Branches ({{ $clinic->branches->count() }})</div>
    @foreach($clinic->branches as $branch)
    <div style="margin-top: 10px; border: 1px solid #e2e8f0; padding: 10px; border-radius: 5px;">
        <strong>{{ $branch->name }}</strong><br>
        <span style="font-size: 11px;">Address: {{ $branch->address_line_1 }}, {{ $branch->state }}</span>
    </div>
    @endforeach
    @endif

    <div class="footer">
        Generated by IVF - APP Management System
    </div>
</body>
</html>